apiVersion: v1
kind: Pod
metadata:
  name: kucc8
spec:
  containers:
  - name: redis
    image: redis
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: memcached
    image: memcached
    ports:
    - containerPort: 80